### PR TITLE
Improve Documentation: Add README and CONTRIBUTING files

### PR DESCRIPTION
**Pull request by yatendra2001**
## Description

This PR adds comprehensive documentation for the `Rocket.Chat Flutter SDK` as well as a CONTRIBUTING.md file for the entire monorepo.

**Changes:**

- Updated the main README.md file with a table of contents, detailed features, and getting started instructions for each package.
- Added README.md files for [Rocket.Chat.Flutter.SDK](https://github.com/RocketChat/Rocket.Chat.Flutter.SDK), detailing features and usage.
- Added a CONTRIBUTING.md file with guidelines for setting up the development environment, contributing code, and submitting pull requests.

These changes aim to make it easier for new contributors to get started with the project and to provide clear instructions on how to use each package.

## Related Issue

#4

### CODE REVIEW

**Review by Sing-Li — CHANGES_REQUESTED** [review]
>  add documentation, in a manner consistent across the entire monorepo
 
 Please:
 
 1.  expand the current README.md to cover the monorepo build instructions to both artifacts.   (how to build both, how to build one, where to find artifacts, where to find error logs,  how it integrates with Github Action CI, and where to find logs if CI fails)     And provide breakout links to 2 and 3 below
 2.   add a README.md at the  EmbeddedChat package level, describing in more detail that project - but also give build instructions on this artifact alone and where to find the artifact, where to find errors and so on ....
 3.   add a README.md at the  API package level, describing in more detail that specific project - but also give build instructions on this artifact alone and where to find the artifact, where to find errors and so on ....

**Comment by yatendra2001** [comment]
@Sing-Li Just a quick question on point 1:
Do I cover monorepo build instructions in README.md or CONTRIBUTING.md? WDYT? 

> (how to build both, how to build one, where to find artifacts, where to find error logs, how it integrates with Github Action CI, and where to find logs if CI fails)

I guess above questions might make more sense in CONTRIBUTING.md 

Breakout links and point 2&3 are much needed for sure.

**Comment by Sing-Li** [comment]
Good idea.   CONTRIBUTING.md is a good home for it. 👏    

I think instructions and docs will inevitably get complex, with time, for this project.      That's a very good suggestion!

**Comment by yatendra2001** [comment]
@Sing-Li ,

I have addressed your feedback and made the following updates:

1. Expanded the main CONTRIBUTING.md file to cover monorepo build instructions for both artifacts, including how to build them individually and together, where to find artifacts, where to find error logs, and how the build process integrates with GitHub Actions CI. 

2. I have also added breakout links to the package-specific README.md files.
 
3. Created a detailed README.md file for the EmbeddedChat package, which includes a description of the project, build instructions for the package, and information on where to find artifacts and error logs.
 
4. Created a detailed README.md file for the API package, which includes a description of the project, build instructions for the package, and information on where to find artifacts and error logs.

Thank you for your guidance!

**Review by Sing-Li — APPROVED** [review]
Thanks!   I was slightly confused by the number of files changed.

Seems you've moved a directory and make the CI working to generate the artifacts.

**Comment by yatendra2001** [comment]
Yeah exactly, needed to change a few names of directories in order to be consistent with Melos and CI. Thanks!

**Pull request merged**
